// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVgPuH5wQMwwDIwLR-NeysE_B3JFLi55g',
    appId: '1:624858805333:web:228e86e6977d1633f9d0dc',
    messagingSenderId: '624858805333',
    projectId: 'proud-will-380104',
    authDomain: 'proud-will-380104.firebaseapp.com',
    storageBucket: 'proud-will-380104.appspot.com',
    measurementId: 'G-WBFCQ74EYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCONLGBWiGnRsyaXHVHX-tXVG9NMGpSE0I',
    appId: '1:624858805333:android:c05fc56fa9c17f17f9d0dc',
    messagingSenderId: '624858805333',
    projectId: 'proud-will-380104',
    storageBucket: 'proud-will-380104.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnGjMXhJvXEu3rZGKRchoTw-apkw8NW7k',
    appId: '1:624858805333:ios:5244d5d9a214453df9d0dc',
    messagingSenderId: '624858805333',
    projectId: 'proud-will-380104',
    storageBucket: 'proud-will-380104.appspot.com',
    iosClientId:
        '624858805333-hbejav65tksqg5fq3uf1s5sgs69j47bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.onboardpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnGjMXhJvXEu3rZGKRchoTw-apkw8NW7k',
    appId: '1:624858805333:ios:5244d5d9a214453df9d0dc',
    messagingSenderId: '624858805333',
    projectId: 'proud-will-380104',
    storageBucket: 'proud-will-380104.appspot.com',
    iosClientId:
        '624858805333-hbejav65tksqg5fq3uf1s5sgs69j47bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.onboardpro',
  );
}
