name: onboardpro
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  firebase_analytics: ^10.2.0
  path_provider: ^2.0.11
  path: ^1.8.2
  share_plus: ^6.3.0
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.11.0
  intl: ^0.17.0
  firebase_storage: ^11.0.10
  url_launcher: ^6.1.9
  file_picker: ^5.2.5
  flutter_svg: ^1.1.6
  scroll_page_view: ^1.0.2
  google_fonts: ^4.0.1
  onboarding: ^3.1.0
  shared_preferences: ^2.0.17
  pinput: ^2.2.31
  googleapis: ^8.1.0
  googleapis_auth: ^1.4.0
  http: ^0.13.5
  image_picker: ^0.8.7+1
  string_similarity: ^2.0.0
  firebase_ml_vision:  ^0.9.10
  encrypt: ^5.0.1
  govt_documents_validator: ^0.0.1
  flutter_face_api: ^5.1.3
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/icon/icon.png
    - assets/images/icon/
    - assets/images/
    - assets/images/icon/checked.svg
    - assets/images/icon/img1.png
